### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Trengland** [Trengland/prework-study-guide#2]
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

GIVEN a Prework Study Guide website
When I view the study guide
Then I see a dark blue header and footer, and four boxes with a shadow

**Comment by Phalgunsharma** [comment]
> As a boot camp student I want the prework notes to be structured on a webpage So that I can easily find and read the information
> 
> GIVEN a Prework Study Guide website When I view the study guide Then I see a dark blue header and footer, and four boxes with a shadow

https://www.w3schools.com/w3css/defaulT.asp
